# Generated by Django 4.2.7 on 2023-12-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credito',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='credito',
            name='email',
        ),
        migrations.RemoveField(
            model_name='credito',
            name='nasc',
        ),
        migrations.RemoveField(
            model_name='credito',
            name='senha',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cadastro'),
        ),
    ]
