# Generated by Django 4.2.7 on 2023-12-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cadastro_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
