# Generated by Django 4.2.7 on 2023-12-01 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_conta_cliente_transacao_conta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='conta',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cadastro'),
        ),
    ]
