# Generated by Django 4.2.7 on 2023-12-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_emprestimo_conta_alter_emprestimo_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='conta',
            new_name='conta_cliente',
        ),
    ]
