# Generated by Django 4.2.7 on 2023-12-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_credito_renda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='conta',
        ),
    ]
