# Generated by Django 4.2.7 on 2023-12-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_emprestimo_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='conta',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.cadastro', verbose_name='nome_cliente'),
        ),
    ]
