# Generated by Django 4.2.7 on 2023-11-30 19:01

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nasc', models.DateField()),
                ('cpf', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=api.models.Cadastro.upload_imagem_cliente)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta', models.CharField(max_length=10, unique=True)),
                ('limite', models.FloatField(null=True)),
                ('ultima_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('renda', models.FloatField()),
                ('agencia', models.CharField(max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.cadastro', verbose_name='nome_cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('valor', models.FloatField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('conta_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='api.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Saque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_saque', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins_email', to='api.cadastro')),
                ('senha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_senha', to='api.cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('taxa_juros', models.FloatField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_deposito', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.cadastro', verbose_name='nome_cliente')),
                ('renda', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credito', to='api.cliente', verbose_name='renda_cliente')),
            ],
        ),
    ]
