# Generated by Django 4.2.7 on 2023-11-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('valor', models.FloatField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('conta_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='api.cliente', verbose_name='Cliente')),
            ],
        ),
    ]
