# Generated by Django 4.2.7 on 2023-12-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_credito_cpf_remove_credito_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='taxa_juros',
        ),
    ]
