# Generated by Django 4.2.7 on 2023-11-24 16:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Cliente.upload_imagem_cliente),
        ),
    ]
