# Generated by Django 4.2.7 on 2023-12-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_emprestimo_taxa_juros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
