# Generated by Django 4.2.7 on 2023-11-24 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cliente_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='atualizado_em',
            new_name='ultima_movimentacao',
        ),
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=10)),
                ('conta', models.CharField(max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('ultima_movimentacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
    ]
