# Generated by Django 4.2.7 on 2023-12-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transacao_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='conta_cliente',
            new_name='conta',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
    ]
