# Generated by Django 4.2.7 on 2023-11-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_saque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contas',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='saque',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contas'),
        ),
    ]
