# Generated by Django 4.2.7 on 2023-11-27 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_contas_cliente_alter_saque_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saque',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
    ]
