# Generated by Django 4.2.7 on 2023-11-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_saque_conta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saque',
        ),
    ]
