# Generated by Django 4.2.7 on 2023-12-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_emprestimo_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='conta',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
    ]
