<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-11-28 01:55
=======
# Generated by Django 4.2.7 on 2023-11-27 19:44
>>>>>>> ae24f884adee08ad6dc7c9b4f6ed028f167eae77

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='rg',
<<<<<<< HEAD
            field=models.CharField(default='', max_length=20),
=======
            field=models.IntegerField(default='00.000.000.0'),
>>>>>>> ae24f884adee08ad6dc7c9b4f6ed028f167eae77
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cadastro')),
            ],
        ),
    ]
