# Generated by Django 4.2.7 on 2023-11-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_cadastro_rg_credito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='rg',
        ),
    ]
