# Generated by Django 4.2.7 on 2023-11-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_cadastro_rg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credito',
        ),
    ]
