# Generated by Django 4.2.7 on 2023-11-28 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_cadastro_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins_email', to='api.cadastro')),
                ('senha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_senha', to='api.cadastro')),
            ],
        ),
    ]
