# Generated by Django 4.2.7 on 2023-12-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_saldo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saldo',
        ),
    ]
